### ISSUE TITLE
Regarding the evolution of Vitesse framework

### ISSUE THREAD

**Issue by bitsnaps** [antfu-collective/vitesse#540]
### Clear and concise description of the problem

Hello,

As a developer who greatly admires your work on Nuxt.js and Vitesse, I wanted to reach out with some thoughts and suggestions regarding the future of Vitesse.

While Nuxt is an excellent framework, I believe there's a strong case for continuing to develop and expand Vitesse as a lightweight companion framework.

Here are a few key points to consider:

1. Vitesse fills an important niche for smaller projects and microservices architectures where Nuxt may be too heavyweight.

2. Vitesse's flexibility allows it to integrate well with various backend technologies like [Hono](https://github.com/bitsnaps/hono-vue3-vite) and FastAPI, which is especially valuable for AI and Python projects.

3. Vitesse's smaller footprint makes it ideal as a headless framework -agnostic- that can be easily plugged into different environments...

4. Vitesse offers better compatibility with [Deno](https://github.com/nuxt/nuxt/discussions/17474)'s dev mode compared to Nuxt.

5. Continuing work on Vitesse complements rather than competes with Nuxt development.

### Suggested solution

To further enhance Vitesse's appeal and usability, I'd like to propose the following roadmap suggestions:

1. Implement a CLI with autocomplete features, similar to the "... on rails" approach.

2. Create a project initialization wizard with multiple choices, akin to the `create-vue` scaffold but with expanded options.

3. Provide additional project templates covering various combinations of:
   - Languages: `JavaScript`/`TypeScript`
   - UI frameworks: `Tailwind`, `Bootstrap 5`, `DaisyUI`, etc.
   - CSS utilities: `UnoCSS` integration option
   - Backend options: `None`, `Hono`, `Express`, `/api`, `static`, etc.
   - Authentication: `Auth0`, `supabase`, `turso`, `local`, `None`

I believe these enhancements would significantly boost Vitesse's adoption, promote the Vue ecosystem, and encourage more community contributions.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for your kind words to Vitesse and I am glad you like it! Vitesse was initially created for my own needs as a simple, reusable starter template for Vite + Vue. I am glad to see it become more popular, but in the meantime, it has grown a lot out of my initial needs. As I see, Nuxt has a much better abstraction and foundation towards various needs (like your mention, backend, and other integrations) - I see not too much benefits for myself to duplicate the work that I am also working on from the other side.

That said, this is just a template after all, and never meant to be a full-featured framework. I don't have the bandwidth/incentive to support the things you need - but on the other hand, feel free to fork it and maintain your own versions. Cheers
