### ISSUE TITLE
[@vueuse useStorage] Lost data in localStorage when I refresh the page? dev normal. after build deploy error.

### ISSUE THREAD

**Issue by whoooami** [antfu-collective/vitesse#544]
### Describe the bug

When I login in my home page. 
1、authStore.login(data);  // checked the data was save in localStorage.
2、When I click refresh button of chrome. I see the "token" in localStorage change to empty string.

When I run "vite --port 3000 --open" in local. the token is ok.
But When I run "vite-ssg build" and deploy to server. the token is missing when I refresh page.

I tried add ssr, but it still doesn't work. 
```
ssr: {
    noExternal: ['@vueuse/core'], // 确保依赖正常工作
  },
```

```
import { useStorage } from '@vueuse/core'

export const useAuthStore = defineStore('auth', () => {
  const token = useStorage('token', '');

  const login = (user: any) => {
    const { token: newToken, ...userData } = user
    token.value = newToken
  }

  return {
    token,
    login,
  }
})
```

### Reproduction

[test url ](https://izone.idotink.com/test/)
1、open it. use chrome dev tools. set localStorage token anything in application.
2、refresh page. the token value is gone.
tips: dev fine. build deploy to server, lost token.
[reproduction project.](https://github.com/whoooami/vitesse)

### System Info

```Shell
npm: 21.1.0
pnpm: 9.11.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment]
I am sorry this is just a starter template, we only deal with the issue of the template itself - this is not a help form for your questions - please do you own research. Thanks.

**Comment by whoooami** [comment]
> I am sorry this is just a starter template, we only deal with the issue of the template itself - this is not a help form for your questions - please do you own research. Thanks.

Alright, thanks all the same.
